# -*- coding: utf-8 -*-
"""playing with pandas and streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uje4-pRQVRgzEdnHw3liDAVdG6MjR1ZN
"""

import pandas as pd
import streamlit as st

#Load and clean up Data
def loaddata ():
  chapters_df = pd.read_csv ('chapters.csv')
  caucuses_df = pd.read_csv ('caucuses.csv')
  return chapters_df, caucuses_df

def meltcaucuses (caucuses_df):
  #Melts the caucus CSV
  melted_caucuses = caucuses_df.melt (
    id_vars=['Chapter'],
    var_name = 'Caucus',
    value_name= '2025 Voters')
  # Fill blank/NaN values with 0 in the '2025 Voters' column
  melted_caucuses['2025 Voters'] = melted_caucuses['2025 Voters'].fillna(0)
  return melted_caucuses

def prepdata():
  chapters_df, caucuses_df = loaddata()
  melted_caucuses = meltcaucuses(caucuses_df)
  return chapters_df, melted_caucuses

#Set up streamlit environment
def showchart ():
  st.write (chapters_df, melted_caucuses)

if __name__ == "__main__":
    # Capture the returned data
    chapters_data, melted_caucuses_data = prepdata()
    # Pass the data to the showchart function
    showchart(chapters_data, melted_caucuses_data)